---
# tasks file for docker_compose

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: yes

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker_compose_system_arch
  changed_when: false

- name: Get distribution codename
  ansible.builtin.command: lsb_release -cs
  register: docker_compose_distro_codename
  changed_when: false

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_compose_system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ docker_compose_distro_codename.stdout }} stable"
    state: present
    filename: docker
  become: yes

- name: Update apt cache after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes
  notify: Start and enable Docker

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
  when: docker_compose_add_user_to_group | default(true)

- name: Create directory for compose file
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  become: yes
  when: docker_compose_content is defined

- name: Copy Docker Compose file
  ansible.builtin.copy:
    content: "{{ docker_compose_content }}"
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: yes
  when: docker_compose_content is defined
  notify: Restart Docker Compose

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
  become: yes
  when: docker_compose_content is defined and docker_compose_deploy | default(true)
