[project]
name = "tf2-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "ty>=0.0.1a23",
    "nicegui>=3.0.4"
]
